version: 2.1

jobs:
  build:
    environment:
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results

    docker:
      - image: testimio/docker-cli

    steps:
      - checkout

      - run:
          name: Prepare Report Directory
          command: mkdir -p $CIRCLE_TEST_REPORTS/testim/

      - run:
          name: Run Testim Tests on Grid
          command: |
            testim --token "$TESTIM_TOKEN" \
                   --project "$TESTIM_PROJECT_ID" \
                   --user "$TESTIM_USER_ID" \
                   --grid "Testim-Grid" \
                   --mode "grid" \
                   --branch "master" \
                   --suite "Object_Detection" \
                   --report-file "$CIRCLE_TEST_REPORTS/testim/results.xml"

      - store_artifacts:
          path: /tmp/circleci-test-results

      - store_test_results:
          path: /tmp/circleci-test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
