version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.11-browsers

    environment:
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results

    steps:
      - checkout

      - run:
          name: Install Testim CLI
          command: npm install @testim/testim-cli

      - run:
          name: Prepare Report Directory
          command: mkdir -p $CIRCLE_TEST_REPORTS/testim/

      - run:
          name: Run Testim Tests on Selenium Grid (ngrok)
          command: |
            npx testim --token "Ia1z0ZWDuObiRZXALdgPhy2gxgj2CyHpAaO7EXjBFQenPceBlu" \
                       --project "usw2u3yVOkPZQmM1lXQTrNjh" \
                       --user "fUKwQdgzPv7D7IA4rAEn" \
                       --host "https://pretensive-rhonda-indeterminably.ngrok-free.dev/wd/hub" \
                       --browser chrome \
                       --suite "Object_Detection" \
                       --report-file "$CIRCLE_TEST_REPORTS/testim/results.xml"

      - store_artifacts:
          path: /tmp/circleci-test-results

      - store_test_results:
          path: /tmp/circleci-test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
